=== CarmenVigo/SEW-WEBMAGICA/web/XML/about.dtd
<!ELEMENT informacion (interes+)>
<!ELEMENT interes (web, autora)>
<!ATTLIST interes id ID #REQUIRED>
<!ELEMENT web (titulo, origen)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT origen (#PCDATA)>
<!ELEMENT autora (nombre, uo, email)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT uo (#PCDATA)>
<!ELEMENT email (#PCDATA)>

=== CarmenVigo/SEW-WEBMAGICA/web/about.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "about.dtd">
<informacion>
    <interes id="I0">
        <web>
            <titulo>Una web llena de Magia</titulo>
            <origen>Una web llena de Magia nace de las ganas de viajar a Hogwarts, la escuela de Magia y Hechicería preferida por todo mago respetable, y el deseo de que la magia sea real.</origen>
        </web>
        <autora>
            <nombre>Carmen Vigo Rodríguez</nombre>
            <uo>UO264045</uo>
            <email>uo264045@uniovi.es</email>
        </autora>
    </interes>
</informacion>
