=== CarmenVigo/SEW-WEBMAGICA/web/XML/saga.dtd
<!ELEMENT novelas (novela+)>
<!ELEMENT novela (portada, titulo, posicion, autora, datosNovela, datosPelicula, sinopsis)>
<!ATTLIST novela id ID #REQUIRED>
<!ELEMENT portada (#PCDATA)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT posicion (#PCDATA)>
<!ELEMENT autora (#PCDATA)>
<!ELEMENT datosNovela (paginas, publicacion, editorial, puntuacion)>
<!ELEMENT paginas (#PCDATA)>
<!ELEMENT publicacion (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT puntuacion (#PCDATA)>
<!ELEMENT datosPelicula (duracion, estreno, estrellas)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT estreno (#PCDATA)>
<!ELEMENT estrellas (#PCDATA)>
<!ELEMENT sinopsis (#PCDATA)>

=== CarmenVigo/SEW-WEBMAGICA/web/XML/saga-harrypotter.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE libros SYSTEM "saga.dtd">
<novelas>
    <novela id="N0">
        <portada>multimedia/img/hp1.jpg</portada>
        <titulo>Harry Potter y la Piedra Filosofal</titulo>
        <posicion>1/7</posicion>
        <autora>J.K. Rowling</autora>
        <datosNovela>
            <paginas>255</paginas>
            <publicacion>1998</publicacion>
            <editorial>Salamandra</editorial>
            <puntuacion>4,5 de 5 estrellas</puntuacion>
        </datosNovela>
        <datosPelicula>
            <duracion>152 minutos</duracion>
            <estreno>2001</estreno>
            <estrellas>4,4 estrellas de 5</estrellas>
        </datosPelicula>
        <sinopsis>Harry Potter se ha quedado huérfano y vive en casa de sus abominables tíos y del insoportable primo Dudley. Se siente muy triste y solo, hasta que un buen día recibe una carta que cambiará su vida para siempre. En ella le comunican que ha sido aceptado como alumno en el colegio interno Hogwarts de magia y hechicería.
        A partir de ese momento, la suerte de Harry da un vuelco espectacular. En esa escuela tan especial aprenderá encantamientos, trucos fabulosos y tácticas de defensa contra las malas artes. Se convertirá en el campeón escolar de quidditch, especie de fútbol aéreo que se juega montado sobre escobas, y hará un puñado de buenos amigos... aunque también algunos temibles enemigos. Pero, sobre todo, conocerá los secretos que le permitirán cumplir con su destino. Pues, aunque no lo parezca a primera vista, Harry no es un chico común y corriente. ¡Es un verdadero mago!</sinopsis>
    </novela>
     <novela id="N1">
        <portada>multimedia/img/hp2.jpg</portada>
        <titulo>Harry Potter y la Cámara Secreta</titulo>
        <posicion>2/7</posicion>
        <autora>J.K. Rowling</autora>
        <datosNovela>
            <paginas>296</paginas>
            <publicacion>1999</publicacion>
            <editorial>Salamandra</editorial>
            <puntuacion>4,4 de 5 estrellas</puntuacion>
        </datosNovela>
        <datosPelicula>
            <duracion>154 minutos</duracion>
            <estreno>2002</estreno>
            <estrellas>4,4 estrellas de 5</estrellas>
        </datosPelicula>
        <sinopsis>«Hay una conspiración, Harry Potter. Una conspiración para hacer que este año sucedan las cosas más terribles en el Colegio Hogwarts de Magia y Hechicería.»
        El verano de Harry Potter ha incluido el peor cumpleaños de su vida, las funestas advertencias de un elfo doméstico llamado Dobby y el rescate de casa de los Dursley protagonizado por su amigo Ron Weasley al volante de un coche mágico volador. De vuelta en el Colegio Hogwarts de Magia y Hechicería, donde va a empezar su segundo curso, Harry oye unos extraños susurros que resuenan por los pasillos vacíos. Y entonces empiezan los ataques y varios alumnos aparecen petrificados... Por lo visto, las siniestras predicciones de Dobby se están cumpliendo....</sinopsis>
    </novela>
     <novela id="N2">
        <portada>multimedia/img/hp3.jpg</portada>
        <titulo>Harry Potter y el Prisionero de Azcaban</titulo>
        <posicion>3/7</posicion>
        <autora>J.K. Rowling</autora>
        <datosNovela>
            <paginas>360</paginas>
            <publicacion>2000</publicacion>
            <editorial>Salamandra</editorial>
            <puntuacion>4,5 de 5 estrellas</puntuacion>
        </datosNovela>
        <datosPelicula>
            <duracion>137 minutos</duracion>
            <estreno>2004</estreno>
            <estrellas>4,4 estrellas de 5</estrellas>
        </datosPelicula>
        <sinopsis>«Bienvenido al autobús noctámbulo, transporte de emergencia para el brujo abandonado a su suerte. Levante la varita, suba a bordo y lo llevaremos a donde quiera.»
        Cuando el autobús noctámbulo irrumpe en una calle oscura y frena con fuertes chirridos delante de Harry, comienza para él un nuevo curso en Hogwarts, lleno de acontecimientos extraordinarios. Sirius Black, asesino y seguidor de lord Voldemort, se ha fugado, y dicen que va en busca de Harry. En su primera clase de Adivinación, la profesora Trelawney ve un augurio de muerte en las hojas de té de la taza de Harry... Pero quizá lo más aterrador sean los dementores que patrullan por los jardines del colegio, capaces de sorberte el alma con su beso...</sinopsis>
    </novela>
     <novela id="N3">
        <portada>multimedia/img/hp4.jpg</portada>
        <titulo>Harry Potter y el Cáliz de Fuego</titulo>
        <posicion>4/7</posicion>
        <autora>J.K. Rowling</autora>
        <datosNovela>
            <paginas>672</paginas>
            <publicacion>2001</publicacion>
            <editorial>Salamandra</editorial>
            <puntuacion>4,5 de 5 estrellas</puntuacion>
        </datosNovela>
        <datosPelicula>
            <duracion>152 minutos</duracion>
            <estreno>2005</estreno>
            <estrellas>4,4 estrellas de 5</estrellas>
        </datosPelicula>
        <sinopsis>«Habrá tres pruebas, espaciadas en el curso escolar, que medirán a los campeones en muchos aspectos diferentes: sus habilidades mágicas, su osadía, sus dotes de deducción y, por supuesto, su capacidad para sortear el peligro.»
        Se va a celebrar en Hogwarts el Torneo de los Tres Magos. Sólo los alumnos mayores de diecisiete años pueden participar en esta competición, pero, aun así, Harry sueña con ganarla. En Halloween, cuando el cáliz de fuego elige a los campeones, Harry se lleva una sorpresa al ver que su nombre es uno de los escogidos por el cáliz mágico. Durante el torneo deberá enfrentarse a desafíos mortales, dragones y magos tenebrosos, pero con la ayuda de Ron y Hermione, sus mejores amigos, ¡quizá logre salir con vida!</sinopsis>
    </novela>
     <novela id="N4">
        <portada>multimedia/img/hp5.jpg</portada>
        <titulo>Harry Potter y la Orden del Fenix</titulo>
        <posicion>5/7</posicion>
        <autora>J.K. Rowling</autora>
        <datosNovela>
            <paginas>928</paginas>
            <publicacion>2004</publicacion>
            <editorial>Salamandra</editorial>
            <puntuacion>4,5 de 5 estrellas</puntuacion>
        </datosNovela>
        <datosPelicula>
            <duracion>138 minutos</duracion>
            <estreno>2007</estreno>
            <estrellas>4,4 estrellas de 5</estrellas>
        </datosPelicula>
        <sinopsis>«El director cree que no es conveniente que eso continúe ocurriendo. Quiere que te enseñe a cerrar tu mente al Señor Tenebroso.»
        Son malos tiempos para Hogwarts. Tras el ataque de los dementores a su primo Dudley, Harry Potter comprende que Voldemort no se detendrá ante nada para encontrarlo. Muchos niegan que el Señor Tenebroso haya regresado, pero Harry no está solo: una orden secreta se reúne en Grimmauld Place para luchar contra las fuerzas oscuras. Harry debe permitir que el profesor Snape le enseñe a protegerse de las brutales incursiones de Voldemort en su mente. Pero éstas son cada vez más potentes, y a Harry se le está agotando el tiempo...</sinopsis>
    </novela>
     <novela id="N5">
        <portada>multimedia/img/hp6.jpg</portada>
        <titulo>Harry Potter y el Príncipe Mestizo</titulo>
        <posicion>6/7</posicion>
        <autora>J.K. Rowling</autora>
        <datosNovela>
            <paginas>576</paginas>
            <publicacion>2006</publicacion>
            <editorial>Salamandra</editorial>
            <puntuacion>4,5 de 5 estrellas</puntuacion>
        </datosNovela>
        <datosPelicula>
            <duracion>153 minutos</duracion>
            <estreno>2009</estreno>
            <estrellas>4,4 estrellas de 5</estrellas>
        </datosPelicula>
        <sinopsis>Con dieciséis años cumplidos, Harry inicia el sexto curso en Hogwarts en medio de terribles acontecimientos que asolan Inglaterra. Elegido capitán del equipo de quidditch, los ensayos, los exámenes y las chicas ocupan todo su tiempo, pero la tranquilidad dura poco.
        A pesar de los férreos controles de seguridad que protegen la escuela, dos alumnos son brutalmente atacados. Dumbledore sabe que se acerca el momento, anunciado por la Profecía, en que Harry y Voldemort se enfrentarán a muerte: «El único con poder para vencer al Señor Tenebroso se acerca... Uno de los dos debe morir a manos del otro, pues ninguno de los dos podrá vivir mientras siga el otro con vida.»
        El anciano director solicitará la ayuda de Harry y juntos emprenderán peligrosos viajes para intentar debilitar al enemigo, para lo cual el joven mago contará con un viejo libro de pociones perteneciente a un misterioso personaje, alguien que se hace llamar Príncipe Mestizo.</sinopsis>
    </novela>
     <novela id="N6">
        <portada>multimedia/img/hp7.jpg</portada>
        <titulo>Harry Potter y las Reliquias de la Muerte</titulo>
        <posicion>7/7</posicion>
        <autora>J.K. Rowling</autora>
        <datosNovela>
            <paginas>640</paginas>
            <publicacion>2008</publicacion>
            <editorial>Salamandra</editorial>
            <puntuacion>4,6 de 5 estrellas</puntuacion>
        </datosNovela>
        <datosPelicula>
            <duracion>146 y 130</duracion>
            <estreno>2010 y </estreno>
            <estrellas>4,4 estrellas de 5</estrellas>
        </datosPelicula>
        <sinopsis>«Entregadme a Harry Potter -dijo la voz de Voldemort- y nadie sufrirá ningún daño. Entregadme a Harry Potter y dejaré el colegio intacto. Entregadme a Harry Potter y seréis recompensados.»
